services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./public:/var/www/html